# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function to run CoxFM
#' @noRd
#'
init_CoxFM <- function(datalist, paralist, maxiter = 100L, eps = 1e-4) {
    .Call('_PJFM_init_CoxFM', PACKAGE = 'PJFM', datalist, paralist, maxiter, eps)
}

#' Main function to run standard JFM
#' @noRd
#'
PJFM <- function(datalist, paralist, maxiter = 100L, eps = 1e-4) {
    .Call('_PJFM_PJFM', PACKAGE = 'PJFM', datalist, paralist, maxiter, eps)
}

#' Main function to get hessian in PJFM
#' @noRd
#'
PJFM_numH <- function(para_all, datalist, paralist, eps = 1e-4, noMUV = TRUE) {
    .Call('_PJFM_PJFM_numH', PACKAGE = 'PJFM', para_all, datalist, paralist, eps, noMUV)
}

#' Main function to calcuate the predicted scores for JFM
#' @noRd
#'
PJFM_pred <- function(datalist, paralist) {
    .Call('_PJFM_PJFM_pred', PACKAGE = 'PJFM', datalist, paralist)
}

#' Main function to run PJFM given one lasso penalty
#' @noRd
#'
PJFM_covBD <- function(datalist, paralist, gvec, lam, ridge, maxiter = 100L, eps = 1e-4) {
    .Call('_PJFM_PJFM_covBD', PACKAGE = 'PJFM', datalist, paralist, gvec, lam, ridge, maxiter, eps)
}

#' Main function to run PJFM for a sequence of lasso penalties
#' @noRd
#'
PJFM_covBD_seq <- function(datalist, paralist, gvec, nlam, ridge, pmax, min_ratio = 0.001, maxiter = 100L, eps = 1e-4, UseSurvN = TRUE) {
    .Call('_PJFM_PJFM_covBD_seq', PACKAGE = 'PJFM', datalist, paralist, gvec, nlam, ridge, pmax, min_ratio, maxiter, eps, UseSurvN)
}

